In [13]:
# Importaciones
import pandas as pd
import numpy as np 
from word2number import w2n

# Imputación de nulos usando métodos avanzados estadísticos
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import display

pd.set_option('display.max_columns', None)

In [14]:
df = pd.read_csv("Alzheimer Disease and Healthy Aging Data In US.csv", low_memory=False, index_col=0)

In [16]:
df.head()

,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,DataValueTypeID,Data_Value_Type,Data_Value,Data_Value_Alt,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,Geolocation,ClassID,TopicID,QuestionID,LocationID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2
YearStart,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020,2020,HI,Hawaii,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,%,PRCTG,Percentage,26.3,26.3,23.9,29,NaN,Age Group,50-64 years,NaN,NaN,POINT (-157.8577494 21.30485044),C01,TOC11,Q43,15,AGE,5064,OVERALL,OVERALL
2017,2017,ID,Idaho,BRFSS,Mental Health,Lifetime diagnosis of depression,Percentage of older adults with a lifetime dia...,%,PRCTG,Percentage,24.0,24.0,21.2,27,NaN,Age Group,50-64 years,NaN,NaN,POINT (-114.36373 43.68263001),C05,TMC03,Q27,16,AGE,5064,OVERALL,OVERALL
2017,2017,ID,Idaho,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,%,PRCTG,Percentage,35.7,35.7,32.5,39.1,NaN,Age Group,50-64 years,NaN,NaN,POINT (-114.36373 43.68263001),C01,TOC11,Q43,16,AGE,5064,OVERALL,OVERALL
2018,2018,ID,Idaho,BRFSS,Overall Health,Physically unhealthy days (mean number of days),Physically unhealthy days (mean number of days...,Number,MEAN,Mean,4.8,4.8,4,5.5,NaN,Age Group,50-64 years,NaN,NaN,POINT (-114.36373 43.68263001),C01,TOC01,Q08,16,AGE,5064,OVERALL,OVERALL
2020,2020,IN,Indiana,BRFSS,Mental Health,Lifetime diagnosis of depression,Percentage of older adults with a lifetime dia...,%,PRCTG,Percentage,13.7,13.7,12.1,15.4,NaN,Age Group,Overall,Gender,Male,POINT (-86.14996019 39.76691045),C05,TMC03,Q27,18,AGE,AGE_OVERALL,GENDER,MALE

In [20]:
df["Sample_Size"].unique()

array([nan])

In [8]:
df.columns

Index(['YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource', 'Class',
       'Topic', 'Question', 'Data_Value_Unit', 'DataValueTypeID',
       'Data_Value_Type', 'Data_Value', 'Data_Value_Alt',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'Sample_Size',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'Geolocation', 'ClassID', 'TopicID', 'QuestionID',
       'LocationID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2'],
      dtype='object')

In [9]:
#FUNCIONES EXPLORACION#

def exploracion_general (dataframe):
    """Esta función proporciona una descripción personalizada de un DataFrame,
    incluyendo estadísticas descriptivas y tipos de datos de cada columna.
    
    Args:
    df : El DataFrame para el cual se generará la descripción

    Returns:
    La funcion no tiene return pero devuelve varios prints con
    la informacion que necesitamos:
    - describe separados por col numericas y categoricas
    - dtypes por columna
    - shape
    - info
    - total de nulos
    - total de duplicados)"""
       
    print(f"------EXPLORACION DATAFRAME ABC CORPORATION------")
    print("-------Descripción numéricas:---------")
    print(dataframe.describe())
    print("-------Descripción categoricas:---------")
    print(dataframe.describe(include="O"))
    print("------Tipos:---------")
    print(dataframe.dtypes)
    print("------Forma del DataFrame:------")
    print(dataframe.shape)
    print("------Información:---------")
    print(dataframe.info())
    print("------Nulos:---------")
    print(dataframe.isnull().sum())
    print("------Duplicados:---------")
    print(dataframe.duplicated().sum())
    
def exploracion_columna (dataframe):

    for columna in list(dataframe.columns):

        print(f" \n----------- ESTAMOS ANALIZANDO LA COLUMNA: '{columna.upper()}' -----------\n")
        print(f"* Nº de datos: {len(dataframe[columna].to_list())}")
        print(f"* Frecuencia de valores en la columna: \n {dataframe[columna].value_counts()}")
        print(f"* Datos unicos en la columna {len(dataframe[columna].unique())}")
        print(f"* Los valores son de tipo: {type(columna)}")
        print(f"La suma de datos nulos {dataframe[columna].isnull().sum()}")
        print(dataframe[columna].unique())

In [11]:
exploracion_general(df)

------EXPLORACION DATAFRAME ABC CORPORATION------
-------Descripción numéricas:---------
             YearEnd     Data_Value  Data_Value_Alt  Sample_Size  \
count  214462.000000  144629.000000   144629.000000          0.0
mean     2017.634000      37.341956       37.341956          NaN
std         1.778926      25.183017       25.183017          NaN
min      2015.000000       0.000000        0.000000          NaN
25%      2016.000000      15.300000       15.300000          NaN
50%      2018.000000      32.500000       32.500000          NaN
75%      2019.000000      56.800000       56.800000          NaN
max      2020.000000     100.000000      100.000000          NaN

          LocationID
count  214462.000000
mean      800.987821
std      2512.934094
min         1.000000
25%        18.000000
50%        33.000000
75%        49.000000
max      9004.000000
-------Descripción categoricas:---------
       LocationAbbr                     LocationDesc Datasource  \
count        214462                           214462     214462
unique           59                               59          1
top              US  United States, DC & Territories      BRFSS
freq           4644                             4644     214462

                 Class    Topic  \
count           214462   214462
unique               7       39
top     Overall Health  Obesity
freq             71694     8300

                                                 Question Data_Value_Unit  \
count                                              214462          214462
unique                                                 39               2
top     Percentage of older adults who are currently o...               %
freq                                                 8300          197929

       DataValueTypeID Data_Value_Type Low_Confidence_Limit  ...  \
count           214462          214462               144472  ...
unique               2               2                  992  ...
top              PRCTG      Percentage                  4.8  ...
freq            197929          197929                  601  ...

       StratificationCategory2      Stratification2  \
count                   186793               186793
unique                       2                    7
top             Race/Ethnicity  White, non-Hispanic
freq                    134959                27633

                             Geolocation ClassID TopicID QuestionID  \
count                             191413  214462  214462     214462
unique                                54       7      39         39
top     POINT (-120.1550313 44.56744942)     C01   TNC04        Q13
freq                                4565   71694    8300       8300

       StratificationCategoryID1 StratificationID1 StratificationCategoryID2  \
count                     214462            214462                    214462
unique                         1                 3                         3
top                          AGE       AGE_OVERALL                      RACE
freq                      214462             71919                    134959

       StratificationID2
count             214462
unique                 8
top              OVERALL
freq               27669

[4 rows x 23 columns]
------Tipos:---------
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
Datasource                    object
Class                         object
Topic                         object
Question                      object
Data_Value_Unit               object
DataValueTypeID               object
Data_Value_Type               object
Data_Value                   float64
Data_Value_Alt               float64
Low_Confidence_Limit          object
High_Confidence_Limit         object
Sample_Size                  float64
StratificationCategory1       object
Stratification1               object
StratificationCategory2       object
Stratification2               object
Geolocation                   object
ClassID                       object
TopicID                       object
QuestionID                    object
LocationID                     int64
StratificationCategoryID1     object
StratificationID1             object
StratificationCategoryID2     object
StratificationID2             object
dtype: object
------Forma del DataFrame:------
(214462, 28)
------Información:---------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 214462 entries, 2020 to 2018
Data columns (total 28 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   YearEnd                    214462 non-null  int64
 1   LocationAbbr               214462 non-null  object
 2   LocationDesc               214462 non-null  object
 3   Datasource                 214462 non-null  object
 4   Class                      214462 non-null  object
 5   Topic                      214462 non-null  object
 6   Question                   214462 non-null  object
 7   Data_Value_Unit            214462 non-null  object
 8   DataValueTypeID            214462 non-null  object
 9   Data_Value_Type            214462 non-null  object
 10  Data_Value                 144629 non-null  float64
 11  Data_Value_Alt             144629 non-null  float64
 12  Low_Confidence_Limit       144472 non-null  object
 13  High_Confidence_Limit      144472 non-null  object
 14  Sample_Size                0 non-null       float64
 15  StratificationCategory1    214462 non-null  object
 16  Stratification1            214462 non-null  object
 17  StratificationCategory2    186793 non-null  object
 18  Stratification2            186793 non-null  object
 19  Geolocation                191413 non-null  object
 20  ClassID                    214462 non-null  object
 21  TopicID                    214462 non-null  object
 22  QuestionID                 214462 non-null  object
 23  LocationID                 214462 non-null  int64
 24  StratificationCategoryID1  214462 non-null  object
 25  StratificationID1          214462 non-null  object
 26  StratificationCategoryID2  214462 non-null  object
 27  StratificationID2          214462 non-null  object
dtypes: float64(3), int64(2), object(23)
memory usage: 47.5+ MB
None
------Nulos:---------
YearEnd                           0
LocationAbbr                      0
LocationDesc                      0
Datasource                        0
Class                             0
Topic                             0
Question                          0
Data_Value_Unit                   0
DataValueTypeID                   0
Data_Value_Type                   0
Data_Value                    69833
Data_Value_Alt                69833
Low_Confidence_Limit          69990
High_Confidence_Limit         69990
Sample_Size                  214462
StratificationCategory1           0
Stratification1                   0
StratificationCategory2       27669
Stratification2               27669
Geolocation                   23049
ClassID                           0
TopicID                           0
QuestionID                        0
LocationID                        0
StratificationCategoryID1         0
StratificationID1                 0
StratificationCategoryID2         0
StratificationID2                 0
dtype: int64
------Duplicados:---------
2859

In [12]:
exploracion_columna(df)

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'YEAREND' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 2020    46966
2015    35020
2019    34354
2016    34145
2017    33429
2018    30548
Name: YearEnd, dtype: int64
* Datos unicos en la columna 6
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
[2020 2017 2018 2019 2015 2016]

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'LOCATIONABBR' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 US      4644
WEST    4638
NRE     4614
MDW     4611
OR      4565
NY      4557
SOU     4542
UT      4222
OH      3955
GA      3951
MD      3919
HI      3907
TN      3879
MI      3796
VA      3758
FL      3753
ME      3733
TX      3699
NV      3696
DC      3684
WV      3682
MS      3677
PA      3648
NM      3635
AL      3633
KY      3623
AK      3611
SC      3592
NJ      3589
AZ      3582
MO      3573
IL      3571
IN      3570
WI      3569
LA      3563
MN      3555
NE      3546
CT      3543
RI      3534
OK      3526
SD      3526
ND      3514
KS      3510
ID      3507
IA      3501
AR      3498
WY      3494
CA      3447
CO      3390
NC      3349
WA      3348
MT      3348
DE      3346
NH      3284
VT      3278
MA      3174
PR      2797
GU      2703
VI       503
Name: LocationAbbr, dtype: int64
* Datos unicos en la columna 59
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
['HI' 'ID' 'IN' 'IA' 'KS' 'KY' 'ME' 'MDW' 'NRE' 'SOU' 'WEST' 'WI' 'WY'
 'AL' 'AZ' 'AK' 'AR' 'CO' 'CT' 'GA' 'GU' 'IL' 'MD' 'CA' 'FL' 'DC' 'DE'
 'LA' 'MS' 'MO' 'NV' 'ND' 'NY' 'OK' 'OH' 'MA' 'MI' 'MT' 'NE' 'MN' 'SD'
 'TN' 'SC' 'NM' 'NH' 'NJ' 'NC' 'OR' 'PA' 'PR' 'RI' 'TX' 'UT' 'US' 'WA'
 'VT' 'VA' 'WV' 'VI']

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'LOCATIONDESC' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 United States, DC & Territories    4644
West                               4638
Northeast                          4614
Midwest                            4611
Oregon                             4565
New York                           4557
South                              4542
Utah                               4222
Ohio                               3955
Georgia                            3951
Maryland                           3919
Hawaii                             3907
Tennessee                          3879
Michigan                           3796
Virginia                           3758
Florida                            3753
Maine                              3733
Texas                              3699
Nevada                             3696
District of Columbia               3684
West Virginia                      3682
Mississippi                        3677
Pennsylvania                       3648
New Mexico                         3635
Alabama                            3633
Kentucky                           3623
Alaska                             3611
South Carolina                     3592
New Jersey                         3589
Arizona                            3582
Missouri                           3573
Illinois                           3571
Indiana                            3570
Wisconsin                          3569
Louisiana                          3563
Minnesota                          3555
Nebraska                           3546
Connecticut                        3543
Rhode Island                       3534
Oklahoma                           3526
South Dakota                       3526
North Dakota                       3514
Kansas                             3510
Idaho                              3507
Iowa                               3501
Arkansas                           3498
Wyoming                            3494
California                         3447
Colorado                           3390
North Carolina                     3349
Washington                         3348
Montana                            3348
Delaware                           3346
New Hampshire                      3284
Vermont                            3278
Massachusetts                      3174
Puerto Rico                        2797
Guam                               2703
Virgin Islands                      503
Name: LocationDesc, dtype: int64
* Datos unicos en la columna 59
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
['Hawaii' 'Idaho' 'Indiana' 'Iowa' 'Kansas' 'Kentucky' 'Maine' 'Midwest'
 'Northeast' 'South' 'West' 'Wisconsin' 'Wyoming' 'Alabama' 'Arizona'
 'Alaska' 'Arkansas' 'Colorado' 'Connecticut' 'Georgia' 'Guam' 'Illinois'
 'Maryland' 'California' 'Florida' 'District of Columbia' 'Delaware'
 'Louisiana' 'Mississippi' 'Missouri' 'Nevada' 'North Dakota' 'New York'
 'Oklahoma' 'Ohio' 'Massachusetts' 'Michigan' 'Montana' 'Nebraska'
 'Minnesota' 'South Dakota' 'Tennessee' 'South Carolina' 'New Mexico'
 'New Hampshire' 'New Jersey' 'North Carolina' 'Oregon' 'Pennsylvania'
 'Puerto Rico' 'Rhode Island' 'Texas' 'Utah'
 'United States, DC & Territories' 'Washington' 'Vermont' 'Virginia'
 'West Virginia' 'Virgin Islands']

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'DATASOURCE' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 BRFSS    214462
Name: Datasource, dtype: int64
* Datos unicos en la columna 1
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
['BRFSS']

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'CLASS' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 Overall Health                         71694
Screenings and Vaccines                46867
Nutrition/Physical Activity/Obesity    24851
Cognitive Decline                      19180
Caregiving                             18671
Mental Health                          16600
Smoking and Alcohol Use                16599
Name: Class, dtype: int64
* Datos unicos en la columna 7
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
['Overall Health' 'Mental Health' 'Smoking and Alcohol Use'
 'Screenings and Vaccines' 'Cognitive Decline'
 'Nutrition/Physical Activity/Obesity' 'Caregiving']

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'TOPIC' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 Obesity                                                                                                   8300
Influenza vaccine within past year                                                                        8300
Physically unhealthy days (mean number of days)                                                           8300
Frequent mental distress                                                                                  8300
Current smoking                                                                                           8300
Lifetime diagnosis of depression                                                                          8300
No leisure-time physical activity within past month                                                       8300
Self-rated health (fair to poor health)                                                                   8299
Self-rated health (good to excellent health)                                                              8299
Binge drinking within past 30 days                                                                        8299
Ever had pneumococcal vaccine                                                                             8268
Recent activity limitations in past month                                                                 8233
Disability status, including sensory or mobility limitations                                              6917
Arthritis among older adults                                                                              5511
Fair or poor health among older adults with arthritis                                                     5447
Subjective cognitive decline or memory loss among older adults                                            5088
Diabetes screening within past 3 years                                                                    4808
Talked with health care professional about subjective cognitive decline or memory loss                    4700
Need assistance with day-to-day activities because of subjective cognitive decline or memory loss         4696
Functional difficulties associated with subjective cognitive decline or memory loss among older adults    4696
Fall with injury within last year                                                                         4173
Colorectal cancer screening                                                                               4173
Oral health:  tooth retention                                                                             4172
Prevalence of sufficient sleep                                                                            4171
Eating 3 or more vegetables daily                                                                         4127
High blood pressure ever                                                                                  4127
Cholesterol checked in past 5 years                                                                       4127
Eating 2 or more fruits daily                                                                             4124
Taking medication for high blood pressure                                                                 4108
Severe joint pain among older adults with arthritis                                                       4064
Provide care for a friend or family member in past month                                                  3848
Expect to provide care for someone in the next two years                                                  3797
Provide care for someone with cognitive impairment within the past month                                  3682
Duration of caregiving among older adults                                                                 3681
Intensity of caregiving among older adults                                                                3663
Up-to-date with recommended vaccines and screenings - Women                                               3280
Up-to-date with recommended vaccines and screenings - Men                                                 3271
Mammogram within past 2 years                                                                             3271
Pap test within past 3 years                                                                              3242
Name: Topic, dtype: int64
* Datos unicos en la columna 39
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
['Arthritis among older adults' 'Lifetime diagnosis of depression'
 'Physically unhealthy days (mean number of days)'
 'Prevalence of sufficient sleep'
 'Fair or poor health among older adults with arthritis'
 'Frequent mental distress' 'Fall with injury within last year'
 'Recent activity limitations in past month'
 'Binge drinking within past 30 days'
 'Diabetes screening within past 3 years'
 'Talked with health care professional about subjective cognitive decline or memory loss'
 'Disability status, including sensory or mobility limitations'
 'Ever had pneumococcal vaccine' 'Influenza vaccine within past year'
 'No leisure-time physical activity within past month'
 'Pap test within past 3 years'
 'Duration of caregiving among older adults'
 'Up-to-date with recommended vaccines and screenings - Men'
 'Eating 2 or more fruits daily' 'Obesity' 'Current smoking'
 'Provide care for a friend or family member in past month'
 'Need assistance with day-to-day activities because of subjective cognitive decline or memory loss'
 'Expect to provide care for someone in the next two years'
 'Oral health:  tooth retention'
 'Self-rated health (good to excellent health)'
 'Taking medication for high blood pressure'
 'Self-rated health (fair to poor health)'
 'Eating 3 or more vegetables daily' 'Colorectal cancer screening'
 'Mammogram within past 2 years'
 'Up-to-date with recommended vaccines and screenings - Women'
 'Cholesterol checked in past 5 years'
 'Functional difficulties associated with subjective cognitive decline or memory loss among older adults'
 'Severe joint pain among older adults with arthritis'
 'High blood pressure ever'
 'Provide care for someone with cognitive impairment within the past month'
 'Intensity of caregiving among older adults'
 'Subjective cognitive decline or memory loss among older adults']

----------- ESTAMOS ANALIZANDO LA COLUMNA: 'QUESTION' -----------

* Nº de datos: 214462
* Frecuencia de valores en la columna:
 Percentage of older adults who are currently obese, with a body mass index (BMI) of 30 or more                                                                               8300
Percentage of older adults who reported influenza vaccine within the past year                                                                                               8300
Physically unhealthy days (mean number of days in past month)                                                                                                                8300
Percentage of older adults who are experiencing frequent mental distress                                                                                                     8300
Percentage of older adults who have smoked at least 100 cigarettes in their entire life and still smoke every day or some days                                               8300
Percentage of older adults with a lifetime diagnosis of depression                                                                                                           8300
Percentage of older adults who have not had any leisure time physical activity in the past month                                                                             8300
Percentage of older adults who self-reported that their health is "fair" or "poor"                                                                                           8299
Percentage of older adults who self-reported that their health is "good", "very good", or "excellent"                                                                        8299
Percentage of older adults who reported binge drinking within the past 30 days                                                                                               8299
Percentage of at risk adults (have diabetes, asthma, cardiovascular disease or currently smoke) who ever had a pneumococcal vaccine                                          8268
Mean number of days with activity limitations in the past month                                                                                                              8233
Percentage of older adults who report having a disability (includes limitations related to sensory or mobility impairments or a physical, mental, or emotional condition)    6917
Percentage of older adults ever told they have arthritis                                                                                                                     5511
Fair or poor health among older adults with doctor-diagnosed arthritis                                                                                                       5447
Percentage of older adults who reported subjective cognitive decline or memory loss that is happening more often or is getting worse in the preceding 12 months              5088
Percentage of older adults without diabetes who reported a blood sugar or diabetes test within 3 years                                                                       4808
Percentage of older adults with subjective cognitive decline or memory loss who reported talking with a health care professional about it                                    4700
Percentage of older adults who reported that as a result of subjective cognitive decline or memory loss that they need assistance with day-to-day activities                 4696
Percentage of older adults who reported subjective cognitive decline or memory loss that interferes with their ability to engage in social activities or household chores    4696
Percentage of older adults who have fallen and sustained an injury within last year                                                                                          4173
Percentage of older adults who had either a home blood stool test within the past year or a sigmoidoscopy or colonoscopy within the past 10 years                            4173
Percentage of older adults who report having lost 5 or fewer teeth due to decay or gum disease                                                                               4172
Percentage of older adults getting sufficient sleep (>6 hours)                                                                                                               4171
Percentage of older adults who are eating 3 or more vegetables daily                                                                                                         4127
Percentage of older adults who have ever been told by a health professional that they have high blood pressure                                                               4127
Percentage of older adults who had a cholesterol screening within the past 5 years                                                                                           4127
Percentage of older adults who are eating 2 or more fruits daily                                                                                                             4124
Percentage of older adults who have been told they have high blood pressure who report currently taking medication for their high blood pressure                             4108
Severe joint pain due to arthritis among older adults with doctor-diagnosed arthritis                                                                                        4064
Percentage of older adults who provided care for a friend or family member within the past month                                                                             3848
Percentage of older adults currently not providing care who expect to provide care for someone with health problems in the next two years                                    3797
Percentage of older adults who provided care for someone with dementia or other cognitive impairment within the past month                                                   3682
Percentage of older adults who provided care to a friend or family member for six months or more                                                                             3681
Average of 20 or more hours of care per week provided to a friend or family member                                                                                           3663
Percentage of older adult women who are up to date with select clinical preventive services                                                                                  3280
Percentage of older adult men who are up to date with select clinical preventive services                                                                                    3271
Percentage of older adult women who have received a mammogram within the past 2 years                                                                                        3271
Percentage of older adult women with an intact cervix who had a Pap test within the past 3 years                                                                             3242
Name: Question, dtype: int64
* Datos unicos en la columna 39
* Los valores son de tipo: <class 'str'>
La suma de datos nulos 0
['Percentage of older adults ever told they have arthritis'
 'Percentage of older adults with a lifetime diagnosis of depression'
 'Physically unhealthy days (mean number of days in past month)'
 'Percentage of older adults getting sufficient sleep (>6 hours)'

In [22]:
columns_to_drop = ["LocationAbbr", "Data_Value_Unit", "Data_Value_Type", "Data_Value_Alt", 
                   "Sample_Size", "StratificationCategory2", "Stratification2", 
                   "StratificationCategoryID1", "StratificationID1"]

# Eliminar las columnas especificadas
df = df.drop(columns=columns_to_drop)

In [23]:
df.columns

Index(['YearEnd', 'LocationDesc', 'Datasource', 'Class', 'Topic', 'Question',
       'DataValueTypeID', 'Data_Value', 'Low_Confidence_Limit',
       'High_Confidence_Limit', 'StratificationCategory1', 'Stratification1',
       'Geolocation', 'ClassID', 'TopicID', 'QuestionID', 'LocationID',
       'StratificationCategoryID2', 'StratificationID2'],
      dtype='object')

In [ ]:
# Gestión de duplicados
# df.drop_duplicates

In [ ]:
# Gestión de nulos
# df = df.dropna()  # Elimina filas con valores nulos

In [ ]:
# Renombrar columnas
# df = df.rename(columns={
    'YearEnd': 'Year_End',
    'LocationAbbr': 'Location_Abbr',
    'LocationDesc': 'Location_Description',
    'Class': 'Data_Class',
    'Topic': 'Data_Topic',
    'Question': 'Data_Question',
    'StratificationCategory1': 'Stratification_Category',
    'Stratification1': 'Stratification'
})

In [ ]:
# JUNTAMOS COLUMNAS: YEARSTART Y YEAREND???

In [ ]:
# Guardar el cvs limpio
# df_cleaned.to_csv('alzheimer_data_cleaned.csv', index=False)